### ISSUE TITLE
Before we share this example (in a week?), your comments would be appreciated

### ISSUE THREAD

**Issue by raiph** [niner/Inline-Python#38]
Please see https://www.reddit.com/r/rakulang/comments/ev29f4/wheres_a_good_community_for_raku/fgjz39b/ for the example, and perhaps glance at the comments before and after it for context.

Please feel free to close this issue if you wish to do so (with or without comment).

That said, a comment such as "looks good to me" would be helpful, and, conversely, if you don't comment, I plan to close this issue shortly after we share the example if not before.

**Comment by bazzaar** [comment]
Raiph, please see issue #36 , as far as I am aware Inline::Python has been out of action for almost a year for new Perl6/Raku releases during that time. I wasn't able to install it with zef onto Rakudo version 2019.11 built on MoarVM version 2019.11. I did last have it working on 2018.11, and I had some working perl6 scripts for time series analysis and plotting using python's matplotlib, maybe that's the perl6 version that b2gills is running, so that he could code his periodictable wrapper. It uses an Inline::Python instance, and so needs Inline::Python to be installed and fully functioning. I've resorted to learning python, pandas, jupyter notebook, ipywidgets, and vitual environment management with pipenv, something I never thought I'd do. I have to say I can see why it's so popular with the scientific community.

**Comment by niner** [comment]
Inline::Python is really lacking some love. I wrote it half a year or so after Inline::Perl5 and initially developed them in tandem. But I stopped working on Inline::Python pretty soon as the whole endeavor is less development and more research. I didn't know what the best way was to integrate any language with Raku, so I had to try out several different approaches and refactored a lot. Doing that for two modules just cost too much time, so I concentrated on Inline::Perl5 first and figured that I'll pretty much rewrite Inline::Python once I know what the best way is.

By now I have a good picture. The meta class workes nicely, I've solved inheritance and reference counting and even precompilation. So I don't think Inline::Perl5's architecture will change much anymore. It can now serve as a reasonable template for other language integrators. What I now need is time and/or help to catch up with Inline::Python.

**Comment by raiph** [comment]
Thank you @bazzaar and @niner for your thorough and helpful comments.

@niner I wrote this issue in the hope of getting clarity about the status of Inline::Python. I now feel I have it; have expressed my new perspective in [a comment in the reddit thread linking to this issue](https://www.reddit.com/r/rakulang/comments/ev29f4/wheres_a_good_community_for_raku/fh8wu86/); and will now close this issue.

Thanks!
